server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  # for POC only, later this should move to cpi-ri module
  jpa:
    hibernate:
    ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
    username: ${USERNAME}
    password: ${PWD}
    driverClassName: org.mariadb.jdbc.Driver

logging:
  level:
    org:
      springframework: INFO